# trace generated using paraview version 6.0.1
#import paraview
#paraview.compatibility.major = 6
#paraview.compatibility.minor = 0

#### import the simple module from the paraview
from paraview.simple import *
#### disable automatic camera reset on 'Show'
paraview.simple._DisableFirstRenderCameraReset()

# get active source.
afoam = GetActiveSource()

# Properties modified on afoam
afoam.MeshRegions = ['patch/DefaultFaces']

# get active view
renderView1 = GetActiveViewOrCreate('RenderView')

# update the view to ensure updated data information
renderView1.Update()

# get display properties
afoamDisplay = GetRepresentation(afoam, view=renderView1)

# get color transfer function/color map for 'p'
pLUT = GetColorTransferFunction('p')

# get opacity transfer function/opacity map for 'p'
pPWF = GetOpacityTransferFunction('p')

# create a new 'Calculator'
calculator1 = Calculator(registrationName='Calculator1', Input=afoam)
calculator1.Set(
    AttributeType='Cell Data',
    CoordinateResults=0,
    ResultNormals=0,
    ResultTCoords=0,
    ResultArrayName='Result',
    Function='',
    ReplaceInvalidResults=1,
    ReplacementValue=0.0,
    ResultArrayType='Double',
)

# Properties modified on calculator1
calculator1.Set(
    ResultArrayName='abs(U_0)',
    Function='abs(U_0)',
)

# show data in view
calculator1Display = Show(calculator1, renderView1, 'GeometryRepresentation')

# get color transfer function/color map for 'absU_0'
absU_0LUT = GetColorTransferFunction('absU_0')

# trace defaults for the display properties.
calculator1Display.Set(
    Selection=None,
    Representation='Surface',
    ColorArrayName=['CELLS', 'abs(U_0)'],
    LookupTable=absU_0LUT,
    MapScalars=1,
    MultiComponentsMapping=0,
    InterpolateScalarsBeforeMapping=1,
    UseNanColorForMissingArrays=0,
    Opacity=1.0,
    PointSize=2.0,
    LineWidth=1.0,
    RenderLinesAsTubes=0,
    RenderPointsAsSpheres=0,
    DisableLighting=0,
    Diffuse=1.0,
    Interpolation='Gouraud',
    Specular=0.0,
    SpecularColor=[1.0, 1.0, 1.0],
    SpecularPower=100.0,
    Luminosity=0.0,
    Ambient=0.0,
    Roughness=0.3,
    Metallic=0.0,
    EdgeTint=[1.0, 1.0, 1.0],
    Anisotropy=0.0,
    AnisotropyRotation=0.0,
    BaseIOR=1.5,
    CoatStrength=0.0,
    CoatIOR=2.0,
    CoatRoughness=0.0,
    CoatColor=[1.0, 1.0, 1.0],
    SelectNormalArray='None',
    SelectTangentArray='None',
    ComputePointNormals=0,
    Splitting=1,
    FeatureAngle=30.0,
    SelectTCoordArray='None',
    Texture=None,
    RepeatTextures=1,
    InterpolateTextures=0,
    SeamlessU=0,
    SeamlessV=0,
    UseMipmapTextures=0,
    ShowTexturesOnBackface=1,
    BaseColorTexture=None,
    NormalTexture=None,
    NormalScale=1.0,
    CoatNormalTexture=None,
    CoatNormalScale=1.0,
    MaterialTexture=None,
    OcclusionStrength=1.0,
    AnisotropyTexture=None,
    EmissiveTexture=None,
    EmissiveFactor=[1.0, 1.0, 1.0],
    TextureTransform='Transform2',
    EdgeOpacity=1.0,
    BackfaceRepresentation='Follow Frontface',
    BackfaceAmbientColor=[1.0, 1.0, 1.0],
    BackfaceOpacity=1.0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    Origin=[0.0, 0.0, 0.0],
    CoordinateShiftScaleMethod='Always Auto Shift Scale',
    CoordinateSystem='Navigable',
    Pickable=1,
    Triangulate=0,
    UseShaderReplacements=0,
    ShaderReplacements='',
    NonlinearSubdivisionLevel=1,
    MatchBoundariesIgnoringCellOrder=0,
    UseDataPartitions=0,
    OSPRayUseScaleArray='All Approximate',
    OSPRayScaleArray='',
    OSPRayScaleFunction='Piecewise Function',
    OSPRayMaterial='None',
    Assembly='Hierarchy',
    SelectedBlockSelectors=[''],
    BlockSelectors=['/'],
    BlockColors=[],
    BlockColorArrayNames=[],
    BlockLookupTables=[],
    BlockUseSeparateColorMaps=[],
    BlockMapScalars=[],
    BlockInterpolateScalarsBeforeMappings=[],
    BlockOpacities=[],
    BlockMapScalarsGUI=1,
    BlockInterpolateScalarsBeforeMappingsGUI=1,
    BlockOpacitiesGUI=1.0,
    Orient=0,
    OrientationMode='Direction',
    SelectOrientationVectors='U',
    Scaling=0,
    ScaleMode='No Data Scaling Off',
    ScaleFactor=0.005000000074505806,
    SelectScaleArray='abs(U_0)',
    GlyphType='Arrow',
    UseGlyphTable=0,
    GlyphTableIndexArray='abs(U_0)',
    UseCompositeGlyphTable=0,
    UseGlyphCullingAndLOD=0,
    LODValues=[],
    ColorByLODIndex=0,
    GaussianRadius=0.0002500000037252903,
    ShaderPreset='Sphere',
    CustomTriangleScale=3,
    Emissive=0,
    ScaleByArray=0,
    SetScaleArray=[None, ''],
    ScaleArrayComponent=0,
    UseScaleFunction=1,
    ScaleTransferFunction='Piecewise Function',
    OpacityByArray=0,
    OpacityArray=[None, ''],
    OpacityArrayComponent=0,
    OpacityTransferFunction='Piecewise Function',
    DataAxesGrid='Grid Axes Representation',
    SelectionCellLabelBold=0,
    SelectionCellLabelColor=[0.0, 1.0, 0.0],
    SelectionCellLabelFontFamily='Arial',
    SelectionCellLabelFontFile='',
    SelectionCellLabelFontSize=18,
    SelectionCellLabelItalic=0,
    SelectionCellLabelJustification='Left',
    SelectionCellLabelOpacity=1.0,
    SelectionCellLabelShadow=0,
    SelectionPointLabelBold=0,
    SelectionPointLabelColor=[1.0, 1.0, 0.0],
    SelectionPointLabelFontFamily='Arial',
    SelectionPointLabelFontFile='',
    SelectionPointLabelFontSize=18,
    SelectionPointLabelItalic=0,
    SelectionPointLabelJustification='Left',
    SelectionPointLabelOpacity=1.0,
    SelectionPointLabelShadow=0,
    PolarAxes='Polar Axes Representation',
    SelectInputVectors=[None, ''],
    NumberOfSteps=40,
    StepSize=0.25,
    NormalizeVectors=1,
    EnhancedLIC=1,
    ColorMode='Blend',
    LICIntensity=0.8,
    MapModeBias=0.0,
    EnhanceContrast='Off',
    LowLICContrastEnhancementFactor=0.0,
    HighLICContrastEnhancementFactor=0.0,
    LowColorContrastEnhancementFactor=0.0,
    HighColorContrastEnhancementFactor=0.0,
    AntiAlias=0,
    MaskOnSurface=1,
    MaskThreshold=0.0,
    MaskIntensity=0.0,
    MaskColor=[0.5, 0.5, 0.5],
    GenerateNoiseTexture=0,
    NoiseType='Gaussian',
    NoiseTextureSize=128,
    NoiseGrainSize=2,
    MinNoiseValue=0.0,
    MaxNoiseValue=0.8,
    NumberOfNoiseLevels=1024,
    ImpulseNoiseProbability=1.0,
    ImpulseNoiseBackgroundValue=0.0,
    NoiseGeneratorSeed=1,
    CompositeStrategy='AUTO',
    UseLICForLOD=0,
    WriteLog='',
    CustomShader=""" // This custom shader code define a gaussian blur
 // Please take a look into vtkSMPointGaussianRepresentation.cxx
 // for other custom shader examples
 //VTK::Color::Impl
   float dist2 = dot(offsetVCVSOutput.xy,offsetVCVSOutput.xy);
   float gaussian = exp(-0.5*dist2);
   opacity = opacity*gaussian;
""",
)

# init the 'Transform2' selected for 'TextureTransform'
calculator1Display.TextureTransform.Set(
    Translate=[0.0, 0.0, 0.0],
    Rotate=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
)

# init the 'Piecewise Function' selected for 'OSPRayScaleFunction'
calculator1Display.OSPRayScaleFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Arrow' selected for 'GlyphType'
calculator1Display.GlyphType.Set(
    TipResolution=6,
    TipRadius=0.1,
    TipLength=0.35,
    ShaftResolution=6,
    ShaftRadius=0.03,
    Invert=0,
)

# init the 'Piecewise Function' selected for 'ScaleTransferFunction'
calculator1Display.ScaleTransferFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Piecewise Function' selected for 'OpacityTransferFunction'
calculator1Display.OpacityTransferFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Grid Axes Representation' selected for 'DataAxesGrid'
calculator1Display.DataAxesGrid.Set(
    XTitle='X Axis',
    YTitle='Y Axis',
    ZTitle='Z Axis',
    XTitleFontFamily='Arial',
    XTitleFontFile='',
    XTitleBold=0,
    XTitleItalic=0,
    XTitleFontSize=12,
    XTitleShadow=0,
    XTitleOpacity=1.0,
    YTitleFontFamily='Arial',
    YTitleFontFile='',
    YTitleBold=0,
    YTitleItalic=0,
    YTitleFontSize=12,
    YTitleShadow=0,
    YTitleOpacity=1.0,
    ZTitleFontFamily='Arial',
    ZTitleFontFile='',
    ZTitleBold=0,
    ZTitleItalic=0,
    ZTitleFontSize=12,
    ZTitleShadow=0,
    ZTitleOpacity=1.0,
    FacesToRender=63,
    CullBackface=0,
    CullFrontface=1,
    ShowGrid=0,
    ShowEdges=1,
    ShowTicks=1,
    LabelUniqueEdgesOnly=1,
    AxesToLabel=63,
    XLabelFontFamily='Arial',
    XLabelFontFile='',
    XLabelBold=0,
    XLabelItalic=0,
    XLabelFontSize=12,
    XLabelShadow=0,
    XLabelOpacity=1.0,
    YLabelFontFamily='Arial',
    YLabelFontFile='',
    YLabelBold=0,
    YLabelItalic=0,
    YLabelFontSize=12,
    YLabelShadow=0,
    YLabelOpacity=1.0,
    ZLabelFontFamily='Arial',
    ZLabelFontFile='',
    ZLabelBold=0,
    ZLabelItalic=0,
    ZLabelFontSize=12,
    ZLabelShadow=0,
    ZLabelOpacity=1.0,
    XAxisNotation='Mixed',
    XAxisPrecision=2,
    XAxisUseCustomLabels=0,
    XAxisLabels=[],
    YAxisNotation='Mixed',
    YAxisPrecision=2,
    YAxisUseCustomLabels=0,
    YAxisLabels=[],
    ZAxisNotation='Mixed',
    ZAxisPrecision=2,
    ZAxisUseCustomLabels=0,
    ZAxisLabels=[],
    UseCustomBounds=0,
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
)

# init the 'Polar Axes Representation' selected for 'PolarAxes'
calculator1Display.PolarAxes.Set(
    Visibility=0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    EnableCustomBounds=[0, 0, 0],
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    EnableCustomRange=0,
    CustomRange=[0.0, 1.0],
    AutoPole=1,
    PolarAxisVisibility=1,
    RadialAxesVisibility=1,
    DrawRadialGridlines=1,
    PolarArcsVisibility=1,
    DrawPolarArcsGridlines=1,
    NumberOfRadialAxes=0,
    DeltaAngleRadialAxes=45.0,
    NumberOfArcs=5,
    DeltaRangeArcs=0.0,
    CustomMinRadius=1,
    MinimumRadius=0.0,
    CustomMaxRadius=0,
    MaximumRadius=1.0,
    CustomAngles=1,
    MinimumAngle=0.0,
    MaximumAngle=90.0,
    RadialAxesOriginToPolarAxis=1,
    PolarArcResolutionPerDegree=0.2,
    Ratio=1.0,
    EnableOverallColor=1,
    OverallColor=[1.0, 1.0, 1.0],
    PolarAxisColor=[1.0, 1.0, 1.0],
    PolarArcsColor=[1.0, 1.0, 1.0],
    LastRadialAxisColor=[1.0, 1.0, 1.0],
    SecondaryPolarArcsColor=[1.0, 1.0, 1.0],
    SecondaryRadialAxesColor=[1.0, 1.0, 1.0],
    PolarAxisTitleVisibility=1,
    PolarAxisTitle='Radial Distance',
    PolarAxisTitleLocation='Bottom',
    PolarTitleOffset=[20.0, 20.0],
    PolarLabelVisibility=1,
    PolarLabelFormat='%-#6.3g',
    PolarLabelExponentLocation='Labels',
    PolarLabelOffset=10.0,
    PolarExponentOffset=5.0,
    RadialLabelVisibility=1,
    RadialLabelFormat='%-#3.1f',
    RadialLabelLocation='Bottom',
    RadialLabelOffset=[20.0, 0.0],
    RadialUnitsVisibility=1,
    ScreenSize=10.0,
    PolarAxisTitleOpacity=1.0,
    PolarAxisTitleFontFamily='Arial',
    PolarAxisTitleFontFile='',
    PolarAxisTitleBold=0,
    PolarAxisTitleItalic=0,
    PolarAxisTitleShadow=0,
    PolarAxisTitleFontSize=12,
    PolarAxisLabelOpacity=1.0,
    PolarAxisLabelFontFamily='Arial',
    PolarAxisLabelFontFile='',
    PolarAxisLabelBold=0,
    PolarAxisLabelItalic=0,
    PolarAxisLabelShadow=0,
    PolarAxisLabelFontSize=12,
    LastRadialAxisTextOpacity=1.0,
    LastRadialAxisTextFontFamily='Arial',
    LastRadialAxisTextFontFile='',
    LastRadialAxisTextBold=0,
    LastRadialAxisTextItalic=0,
    LastRadialAxisTextShadow=0,
    LastRadialAxisTextFontSize=12,
    SecondaryRadialAxesTextOpacity=1.0,
    SecondaryRadialAxesTextFontFamily='Arial',
    SecondaryRadialAxesTextFontFile='',
    SecondaryRadialAxesTextBold=0,
    SecondaryRadialAxesTextItalic=0,
    SecondaryRadialAxesTextShadow=0,
    SecondaryRadialAxesTextFontSize=12,
    EnableDistanceLOD=1,
    DistanceLODThreshold=0.7,
    EnableViewAngleLOD=1,
    ViewAngleLODThreshold=0.7,
    SmallestVisiblePolarAngle=0.5,
    AllTicksVisibility=1,
    ArcTicksOriginToPolarAxis=1,
    TickLocation='Both',
    AxisTickVisibility=1,
    AxisMinorTickVisibility=0,
    AxisTickMatchesPolarAxes=1,
    DeltaRangeMajor=1.0,
    DeltaRangeMinor=0.5,
    ArcTickVisibility=1,
    ArcMinorTickVisibility=0,
    ArcTickMatchesRadialAxes=1,
    DeltaAngleMajor=10.0,
    DeltaAngleMinor=5.0,
    TickRatioRadiusSize=0.02,
    PolarAxisMajorTickSize=0.0,
    PolarAxisTickRatioSize=0.3,
    PolarAxisMajorTickThickness=1.0,
    PolarAxisTickRatioThickness=0.5,
    LastRadialAxisMajorTickSize=0.0,
    LastRadialAxisTickRatioSize=0.3,
    LastRadialAxisMajorTickThickness=1.0,
    LastRadialAxisTickRatioThickness=0.5,
    ArcMajorTickSize=0.0,
    ArcTickRatioSize=0.3,
    ArcMajorTickThickness=1.0,
    ArcTickRatioThickness=0.5,
    Use2DMode=0,
    UseLogAxis=0,
)

# hide data in view
Hide(afoam, renderView1)

# show color bar/color legend
calculator1Display.SetScalarBarVisibility(renderView1, True)

# update the view to ensure updated data information
renderView1.Update()

# get opacity transfer function/opacity map for 'absU_0'
absU_0PWF = GetOpacityTransferFunction('absU_0')

# get 2D transfer function for 'absU_0'
absU_0TF2D = GetTransferFunction2D('absU_0')

# create a new 'Calculator'
calculator2 = Calculator(registrationName='Calculator2', Input=calculator1)
calculator2.Set(
    AttributeType='Cell Data',
    CoordinateResults=0,
    ResultNormals=0,
    ResultTCoords=0,
    ResultArrayName='Result',
    Function='',
    ReplaceInvalidResults=1,
    ReplacementValue=0.0,
    ResultArrayType='Double',
)

# Properties modified on calculator2
calculator2.Set(
    ResultArrayName='abs(U_1)',
    Function='abs(U_1)',
)

# show data in view
calculator2Display = Show(calculator2, renderView1, 'GeometryRepresentation')

# get color transfer function/color map for 'absU_1'
absU_1LUT = GetColorTransferFunction('absU_1')

# trace defaults for the display properties.
calculator2Display.Set(
    Selection=None,
    Representation='Surface',
    ColorArrayName=['CELLS', 'abs(U_1)'],
    LookupTable=absU_1LUT,
    MapScalars=1,
    MultiComponentsMapping=0,
    InterpolateScalarsBeforeMapping=1,
    UseNanColorForMissingArrays=0,
    Opacity=1.0,
    PointSize=2.0,
    LineWidth=1.0,
    RenderLinesAsTubes=0,
    RenderPointsAsSpheres=0,
    DisableLighting=0,
    Diffuse=1.0,
    Interpolation='Gouraud',
    Specular=0.0,
    SpecularColor=[1.0, 1.0, 1.0],
    SpecularPower=100.0,
    Luminosity=0.0,
    Ambient=0.0,
    Roughness=0.3,
    Metallic=0.0,
    EdgeTint=[1.0, 1.0, 1.0],
    Anisotropy=0.0,
    AnisotropyRotation=0.0,
    BaseIOR=1.5,
    CoatStrength=0.0,
    CoatIOR=2.0,
    CoatRoughness=0.0,
    CoatColor=[1.0, 1.0, 1.0],
    SelectNormalArray='None',
    SelectTangentArray='None',
    ComputePointNormals=0,
    Splitting=1,
    FeatureAngle=30.0,
    SelectTCoordArray='None',
    Texture=None,
    RepeatTextures=1,
    InterpolateTextures=0,
    SeamlessU=0,
    SeamlessV=0,
    UseMipmapTextures=0,
    ShowTexturesOnBackface=1,
    BaseColorTexture=None,
    NormalTexture=None,
    NormalScale=1.0,
    CoatNormalTexture=None,
    CoatNormalScale=1.0,
    MaterialTexture=None,
    OcclusionStrength=1.0,
    AnisotropyTexture=None,
    EmissiveTexture=None,
    EmissiveFactor=[1.0, 1.0, 1.0],
    TextureTransform='Transform2',
    EdgeOpacity=1.0,
    BackfaceRepresentation='Follow Frontface',
    BackfaceAmbientColor=[1.0, 1.0, 1.0],
    BackfaceOpacity=1.0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    Origin=[0.0, 0.0, 0.0],
    CoordinateShiftScaleMethod='Always Auto Shift Scale',
    CoordinateSystem='Navigable',
    Pickable=1,
    Triangulate=0,
    UseShaderReplacements=0,
    ShaderReplacements='',
    NonlinearSubdivisionLevel=1,
    MatchBoundariesIgnoringCellOrder=0,
    UseDataPartitions=0,
    OSPRayUseScaleArray='All Approximate',
    OSPRayScaleArray='',
    OSPRayScaleFunction='Piecewise Function',
    OSPRayMaterial='None',
    Assembly='Hierarchy',
    SelectedBlockSelectors=[''],
    BlockSelectors=['/'],
    BlockColors=[],
    BlockColorArrayNames=[],
    BlockLookupTables=[],
    BlockUseSeparateColorMaps=[],
    BlockMapScalars=[],
    BlockInterpolateScalarsBeforeMappings=[],
    BlockOpacities=[],
    BlockMapScalarsGUI=1,
    BlockInterpolateScalarsBeforeMappingsGUI=1,
    BlockOpacitiesGUI=1.0,
    Orient=0,
    OrientationMode='Direction',
    SelectOrientationVectors='U',
    Scaling=0,
    ScaleMode='No Data Scaling Off',
    ScaleFactor=0.005000000074505806,
    SelectScaleArray='abs(U_1)',
    GlyphType='Arrow',
    UseGlyphTable=0,
    GlyphTableIndexArray='abs(U_1)',
    UseCompositeGlyphTable=0,
    UseGlyphCullingAndLOD=0,
    LODValues=[],
    ColorByLODIndex=0,
    GaussianRadius=0.0002500000037252903,
    ShaderPreset='Sphere',
    CustomTriangleScale=3,
    Emissive=0,
    ScaleByArray=0,
    SetScaleArray=[None, ''],
    ScaleArrayComponent=0,
    UseScaleFunction=1,
    ScaleTransferFunction='Piecewise Function',
    OpacityByArray=0,
    OpacityArray=[None, ''],
    OpacityArrayComponent=0,
    OpacityTransferFunction='Piecewise Function',
    DataAxesGrid='Grid Axes Representation',
    SelectionCellLabelBold=0,
    SelectionCellLabelColor=[0.0, 1.0, 0.0],
    SelectionCellLabelFontFamily='Arial',
    SelectionCellLabelFontFile='',
    SelectionCellLabelFontSize=18,
    SelectionCellLabelItalic=0,
    SelectionCellLabelJustification='Left',
    SelectionCellLabelOpacity=1.0,
    SelectionCellLabelShadow=0,
    SelectionPointLabelBold=0,
    SelectionPointLabelColor=[1.0, 1.0, 0.0],
    SelectionPointLabelFontFamily='Arial',
    SelectionPointLabelFontFile='',
    SelectionPointLabelFontSize=18,
    SelectionPointLabelItalic=0,
    SelectionPointLabelJustification='Left',
    SelectionPointLabelOpacity=1.0,
    SelectionPointLabelShadow=0,
    PolarAxes='Polar Axes Representation',
    SelectInputVectors=[None, ''],
    NumberOfSteps=40,
    StepSize=0.25,
    NormalizeVectors=1,
    EnhancedLIC=1,
    ColorMode='Blend',
    LICIntensity=0.8,
    MapModeBias=0.0,
    EnhanceContrast='Off',
    LowLICContrastEnhancementFactor=0.0,
    HighLICContrastEnhancementFactor=0.0,
    LowColorContrastEnhancementFactor=0.0,
    HighColorContrastEnhancementFactor=0.0,
    AntiAlias=0,
    MaskOnSurface=1,
    MaskThreshold=0.0,
    MaskIntensity=0.0,
    MaskColor=[0.5, 0.5, 0.5],
    GenerateNoiseTexture=0,
    NoiseType='Gaussian',
    NoiseTextureSize=128,
    NoiseGrainSize=2,
    MinNoiseValue=0.0,
    MaxNoiseValue=0.8,
    NumberOfNoiseLevels=1024,
    ImpulseNoiseProbability=1.0,
    ImpulseNoiseBackgroundValue=0.0,
    NoiseGeneratorSeed=1,
    CompositeStrategy='AUTO',
    UseLICForLOD=0,
    WriteLog='',
    CustomShader=""" // This custom shader code define a gaussian blur
 // Please take a look into vtkSMPointGaussianRepresentation.cxx
 // for other custom shader examples
 //VTK::Color::Impl
   float dist2 = dot(offsetVCVSOutput.xy,offsetVCVSOutput.xy);
   float gaussian = exp(-0.5*dist2);
   opacity = opacity*gaussian;
""",
)

# init the 'Transform2' selected for 'TextureTransform'
calculator2Display.TextureTransform.Set(
    Translate=[0.0, 0.0, 0.0],
    Rotate=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
)

# init the 'Piecewise Function' selected for 'OSPRayScaleFunction'
calculator2Display.OSPRayScaleFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Arrow' selected for 'GlyphType'
calculator2Display.GlyphType.Set(
    TipResolution=6,
    TipRadius=0.1,
    TipLength=0.35,
    ShaftResolution=6,
    ShaftRadius=0.03,
    Invert=0,
)

# init the 'Piecewise Function' selected for 'ScaleTransferFunction'
calculator2Display.ScaleTransferFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Piecewise Function' selected for 'OpacityTransferFunction'
calculator2Display.OpacityTransferFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Grid Axes Representation' selected for 'DataAxesGrid'
calculator2Display.DataAxesGrid.Set(
    XTitle='X Axis',
    YTitle='Y Axis',
    ZTitle='Z Axis',
    XTitleFontFamily='Arial',
    XTitleFontFile='',
    XTitleBold=0,
    XTitleItalic=0,
    XTitleFontSize=12,
    XTitleShadow=0,
    XTitleOpacity=1.0,
    YTitleFontFamily='Arial',
    YTitleFontFile='',
    YTitleBold=0,
    YTitleItalic=0,
    YTitleFontSize=12,
    YTitleShadow=0,
    YTitleOpacity=1.0,
    ZTitleFontFamily='Arial',
    ZTitleFontFile='',
    ZTitleBold=0,
    ZTitleItalic=0,
    ZTitleFontSize=12,
    ZTitleShadow=0,
    ZTitleOpacity=1.0,
    FacesToRender=63,
    CullBackface=0,
    CullFrontface=1,
    ShowGrid=0,
    ShowEdges=1,
    ShowTicks=1,
    LabelUniqueEdgesOnly=1,
    AxesToLabel=63,
    XLabelFontFamily='Arial',
    XLabelFontFile='',
    XLabelBold=0,
    XLabelItalic=0,
    XLabelFontSize=12,
    XLabelShadow=0,
    XLabelOpacity=1.0,
    YLabelFontFamily='Arial',
    YLabelFontFile='',
    YLabelBold=0,
    YLabelItalic=0,
    YLabelFontSize=12,
    YLabelShadow=0,
    YLabelOpacity=1.0,
    ZLabelFontFamily='Arial',
    ZLabelFontFile='',
    ZLabelBold=0,
    ZLabelItalic=0,
    ZLabelFontSize=12,
    ZLabelShadow=0,
    ZLabelOpacity=1.0,
    XAxisNotation='Mixed',
    XAxisPrecision=2,
    XAxisUseCustomLabels=0,
    XAxisLabels=[],
    YAxisNotation='Mixed',
    YAxisPrecision=2,
    YAxisUseCustomLabels=0,
    YAxisLabels=[],
    ZAxisNotation='Mixed',
    ZAxisPrecision=2,
    ZAxisUseCustomLabels=0,
    ZAxisLabels=[],
    UseCustomBounds=0,
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
)

# init the 'Polar Axes Representation' selected for 'PolarAxes'
calculator2Display.PolarAxes.Set(
    Visibility=0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    EnableCustomBounds=[0, 0, 0],
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    EnableCustomRange=0,
    CustomRange=[0.0, 1.0],
    AutoPole=1,
    PolarAxisVisibility=1,
    RadialAxesVisibility=1,
    DrawRadialGridlines=1,
    PolarArcsVisibility=1,
    DrawPolarArcsGridlines=1,
    NumberOfRadialAxes=0,
    DeltaAngleRadialAxes=45.0,
    NumberOfArcs=5,
    DeltaRangeArcs=0.0,
    CustomMinRadius=1,
    MinimumRadius=0.0,
    CustomMaxRadius=0,
    MaximumRadius=1.0,
    CustomAngles=1,
    MinimumAngle=0.0,
    MaximumAngle=90.0,
    RadialAxesOriginToPolarAxis=1,
    PolarArcResolutionPerDegree=0.2,
    Ratio=1.0,
    EnableOverallColor=1,
    OverallColor=[1.0, 1.0, 1.0],
    PolarAxisColor=[1.0, 1.0, 1.0],
    PolarArcsColor=[1.0, 1.0, 1.0],
    LastRadialAxisColor=[1.0, 1.0, 1.0],
    SecondaryPolarArcsColor=[1.0, 1.0, 1.0],
    SecondaryRadialAxesColor=[1.0, 1.0, 1.0],
    PolarAxisTitleVisibility=1,
    PolarAxisTitle='Radial Distance',
    PolarAxisTitleLocation='Bottom',
    PolarTitleOffset=[20.0, 20.0],
    PolarLabelVisibility=1,
    PolarLabelFormat='%-#6.3g',
    PolarLabelExponentLocation='Labels',
    PolarLabelOffset=10.0,
    PolarExponentOffset=5.0,
    RadialLabelVisibility=1,
    RadialLabelFormat='%-#3.1f',
    RadialLabelLocation='Bottom',
    RadialLabelOffset=[20.0, 0.0],
    RadialUnitsVisibility=1,
    ScreenSize=10.0,
    PolarAxisTitleOpacity=1.0,
    PolarAxisTitleFontFamily='Arial',
    PolarAxisTitleFontFile='',
    PolarAxisTitleBold=0,
    PolarAxisTitleItalic=0,
    PolarAxisTitleShadow=0,
    PolarAxisTitleFontSize=12,
    PolarAxisLabelOpacity=1.0,
    PolarAxisLabelFontFamily='Arial',
    PolarAxisLabelFontFile='',
    PolarAxisLabelBold=0,
    PolarAxisLabelItalic=0,
    PolarAxisLabelShadow=0,
    PolarAxisLabelFontSize=12,
    LastRadialAxisTextOpacity=1.0,
    LastRadialAxisTextFontFamily='Arial',
    LastRadialAxisTextFontFile='',
    LastRadialAxisTextBold=0,
    LastRadialAxisTextItalic=0,
    LastRadialAxisTextShadow=0,
    LastRadialAxisTextFontSize=12,
    SecondaryRadialAxesTextOpacity=1.0,
    SecondaryRadialAxesTextFontFamily='Arial',
    SecondaryRadialAxesTextFontFile='',
    SecondaryRadialAxesTextBold=0,
    SecondaryRadialAxesTextItalic=0,
    SecondaryRadialAxesTextShadow=0,
    SecondaryRadialAxesTextFontSize=12,
    EnableDistanceLOD=1,
    DistanceLODThreshold=0.7,
    EnableViewAngleLOD=1,
    ViewAngleLODThreshold=0.7,
    SmallestVisiblePolarAngle=0.5,
    AllTicksVisibility=1,
    ArcTicksOriginToPolarAxis=1,
    TickLocation='Both',
    AxisTickVisibility=1,
    AxisMinorTickVisibility=0,
    AxisTickMatchesPolarAxes=1,
    DeltaRangeMajor=1.0,
    DeltaRangeMinor=0.5,
    ArcTickVisibility=1,
    ArcMinorTickVisibility=0,
    ArcTickMatchesRadialAxes=1,
    DeltaAngleMajor=10.0,
    DeltaAngleMinor=5.0,
    TickRatioRadiusSize=0.02,
    PolarAxisMajorTickSize=0.0,
    PolarAxisTickRatioSize=0.3,
    PolarAxisMajorTickThickness=1.0,
    PolarAxisTickRatioThickness=0.5,
    LastRadialAxisMajorTickSize=0.0,
    LastRadialAxisTickRatioSize=0.3,
    LastRadialAxisMajorTickThickness=1.0,
    LastRadialAxisTickRatioThickness=0.5,
    ArcMajorTickSize=0.0,
    ArcTickRatioSize=0.3,
    ArcMajorTickThickness=1.0,
    ArcTickRatioThickness=0.5,
    Use2DMode=0,
    UseLogAxis=0,
)

# hide data in view
Hide(calculator1, renderView1)

# show color bar/color legend
calculator2Display.SetScalarBarVisibility(renderView1, True)

# update the view to ensure updated data information
renderView1.Update()

# get opacity transfer function/opacity map for 'absU_1'
absU_1PWF = GetOpacityTransferFunction('absU_1')

# get 2D transfer function for 'absU_1'
absU_1TF2D = GetTransferFunction2D('absU_1')

# create a new 'Threshold'
threshold1 = Threshold(registrationName='Threshold1', Input=calculator2)
threshold1.Set(
    Scalars=['CELLS', 'abs(U_1)'],
    ComponentMode='Selected',
    SelectedComponent='',
    LowerThreshold=1.3163200307531042e-08,
    UpperThreshold=0.03995930030941963,
    ThresholdMethod='Between',
    AllScalars=1,
    UseContinuousCellRange=0,
    Invert=0,
    MemoryStrategy='Mask Input',
)

# Properties modified on threshold1
threshold1.Set(
    Scalars=['CELLS', 'plasmaIndicator'],
    LowerThreshold=0.5,
    UpperThreshold=1.5,
)

# show data in view
threshold1Display = Show(threshold1, renderView1, 'UnstructuredGridRepresentation')

# trace defaults for the display properties.
threshold1Display.Set(
    Selection=None,
    Representation='Surface',
    ColorArrayName=[None, ''],
    LookupTable=None,
    MapScalars=1,
    MultiComponentsMapping=0,
    InterpolateScalarsBeforeMapping=1,
    UseNanColorForMissingArrays=0,
    Opacity=1.0,
    PointSize=2.0,
    LineWidth=1.0,
    RenderLinesAsTubes=0,
    RenderPointsAsSpheres=0,
    DisableLighting=0,
    Diffuse=1.0,
    Interpolation='Gouraud',
    Specular=0.0,
    SpecularColor=[1.0, 1.0, 1.0],
    SpecularPower=100.0,
    Luminosity=0.0,
    Ambient=0.0,
    Roughness=0.3,
    Metallic=0.0,
    EdgeTint=[1.0, 1.0, 1.0],
    Anisotropy=0.0,
    AnisotropyRotation=0.0,
    BaseIOR=1.5,
    CoatStrength=0.0,
    CoatIOR=2.0,
    CoatRoughness=0.0,
    CoatColor=[1.0, 1.0, 1.0],
    SelectNormalArray='None',
    SelectTangentArray='None',
    ComputePointNormals=0,
    Splitting=1,
    FeatureAngle=30.0,
    SelectTCoordArray='None',
    Texture=None,
    RepeatTextures=1,
    InterpolateTextures=0,
    SeamlessU=0,
    SeamlessV=0,
    UseMipmapTextures=0,
    ShowTexturesOnBackface=1,
    BaseColorTexture=None,
    NormalTexture=None,
    NormalScale=1.0,
    CoatNormalTexture=None,
    CoatNormalScale=1.0,
    MaterialTexture=None,
    OcclusionStrength=1.0,
    AnisotropyTexture=None,
    EmissiveTexture=None,
    EmissiveFactor=[1.0, 1.0, 1.0],
    TextureTransform='Transform2',
    EdgeOpacity=1.0,
    BackfaceRepresentation='Follow Frontface',
    BackfaceAmbientColor=[1.0, 1.0, 1.0],
    BackfaceOpacity=1.0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    Origin=[0.0, 0.0, 0.0],
    CoordinateShiftScaleMethod='Always Auto Shift Scale',
    CoordinateSystem='Navigable',
    Pickable=1,
    Triangulate=0,
    UseShaderReplacements=0,
    ShaderReplacements='',
    NonlinearSubdivisionLevel=1,
    MatchBoundariesIgnoringCellOrder=0,
    UseDataPartitions=0,
    OSPRayUseScaleArray='All Approximate',
    OSPRayScaleArray='',
    OSPRayScaleFunction='Piecewise Function',
    OSPRayMaterial='None',
    Assembly='Hierarchy',
    SelectedBlockSelectors=[''],
    BlockSelectors=['/'],
    BlockColors=[],
    BlockColorArrayNames=[],
    BlockLookupTables=[],
    BlockUseSeparateColorMaps=[],
    BlockMapScalars=[],
    BlockInterpolateScalarsBeforeMappings=[],
    BlockOpacities=[],
    BlockMapScalarsGUI=1,
    BlockInterpolateScalarsBeforeMappingsGUI=1,
    BlockOpacitiesGUI=1.0,
    Orient=0,
    OrientationMode='Direction',
    SelectOrientationVectors='None',
    Scaling=0,
    ScaleMode='No Data Scaling Off',
    ScaleFactor=-2.0000000000000002e+298,
    SelectScaleArray='None',
    GlyphType='Arrow',
    UseGlyphTable=0,
    GlyphTableIndexArray='None',
    UseCompositeGlyphTable=0,
    UseGlyphCullingAndLOD=0,
    LODValues=[],
    ColorByLODIndex=0,
    GaussianRadius=-1e+297,
    ShaderPreset='Sphere',
    CustomTriangleScale=3,
    Emissive=0,
    ScaleByArray=0,
    SetScaleArray=[None, ''],
    ScaleArrayComponent=0,
    UseScaleFunction=1,
    ScaleTransferFunction='Piecewise Function',
    OpacityByArray=0,
    OpacityArray=[None, ''],
    OpacityArrayComponent=0,
    OpacityTransferFunction='Piecewise Function',
    DataAxesGrid='Grid Axes Representation',
    SelectionCellLabelBold=0,
    SelectionCellLabelColor=[0.0, 1.0, 0.0],
    SelectionCellLabelFontFamily='Arial',
    SelectionCellLabelFontFile='',
    SelectionCellLabelFontSize=18,
    SelectionCellLabelItalic=0,
    SelectionCellLabelJustification='Left',
    SelectionCellLabelOpacity=1.0,
    SelectionCellLabelShadow=0,
    SelectionPointLabelBold=0,
    SelectionPointLabelColor=[1.0, 1.0, 0.0],
    SelectionPointLabelFontFamily='Arial',
    SelectionPointLabelFontFile='',
    SelectionPointLabelFontSize=18,
    SelectionPointLabelItalic=0,
    SelectionPointLabelJustification='Left',
    SelectionPointLabelOpacity=1.0,
    SelectionPointLabelShadow=0,
    PolarAxes='Polar Axes Representation',
    ScalarOpacityFunction=None,
    ScalarOpacityUnitDistance=1.0,
    UseSeparateOpacityArray=0,
    OpacityArrayName=['FIELD', 'CasePath'],
    OpacityComponent=0,
    SelectMapper='Projected tetra',
    SamplingDimensions=[128, 128, 128],
    UseFloatingPointFrameBuffer=1,
    SelectInputVectors=[None, ''],
    NumberOfSteps=40,
    StepSize=0.25,
    NormalizeVectors=1,
    EnhancedLIC=1,
    ColorMode='Blend',
    LICIntensity=0.8,
    MapModeBias=0.0,
    EnhanceContrast='Off',
    LowLICContrastEnhancementFactor=0.0,
    HighLICContrastEnhancementFactor=0.0,
    LowColorContrastEnhancementFactor=0.0,
    HighColorContrastEnhancementFactor=0.0,
    AntiAlias=0,
    MaskOnSurface=1,
    MaskThreshold=0.0,
    MaskIntensity=0.0,
    MaskColor=[0.5, 0.5, 0.5],
    GenerateNoiseTexture=0,
    NoiseType='Gaussian',
    NoiseTextureSize=128,
    NoiseGrainSize=2,
    MinNoiseValue=0.0,
    MaxNoiseValue=0.8,
    NumberOfNoiseLevels=1024,
    ImpulseNoiseProbability=1.0,
    ImpulseNoiseBackgroundValue=0.0,
    NoiseGeneratorSeed=1,
    CompositeStrategy='AUTO',
    UseLICForLOD=0,
    WriteLog='',
    CustomShader=""" // This custom shader code define a gaussian blur
 // Please take a look into vtkSMPointGaussianRepresentation.cxx
 // for other custom shader examples
 //VTK::Color::Impl
   float dist2 = dot(offsetVCVSOutput.xy,offsetVCVSOutput.xy);
   float gaussian = exp(-0.5*dist2);
   opacity = opacity*gaussian;
""",
)

# init the 'Transform2' selected for 'TextureTransform'
threshold1Display.TextureTransform.Set(
    Translate=[0.0, 0.0, 0.0],
    Rotate=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
)

# init the 'Piecewise Function' selected for 'OSPRayScaleFunction'
threshold1Display.OSPRayScaleFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Arrow' selected for 'GlyphType'
threshold1Display.GlyphType.Set(
    TipResolution=6,
    TipRadius=0.1,
    TipLength=0.35,
    ShaftResolution=6,
    ShaftRadius=0.03,
    Invert=0,
)

# init the 'Piecewise Function' selected for 'ScaleTransferFunction'
threshold1Display.ScaleTransferFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Piecewise Function' selected for 'OpacityTransferFunction'
threshold1Display.OpacityTransferFunction.Set(
    Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0],
    UseLogScale=0,
)

# init the 'Grid Axes Representation' selected for 'DataAxesGrid'
threshold1Display.DataAxesGrid.Set(
    XTitle='X Axis',
    YTitle='Y Axis',
    ZTitle='Z Axis',
    XTitleFontFamily='Arial',
    XTitleFontFile='',
    XTitleBold=0,
    XTitleItalic=0,
    XTitleFontSize=12,
    XTitleShadow=0,
    XTitleOpacity=1.0,
    YTitleFontFamily='Arial',
    YTitleFontFile='',
    YTitleBold=0,
    YTitleItalic=0,
    YTitleFontSize=12,
    YTitleShadow=0,
    YTitleOpacity=1.0,
    ZTitleFontFamily='Arial',
    ZTitleFontFile='',
    ZTitleBold=0,
    ZTitleItalic=0,
    ZTitleFontSize=12,
    ZTitleShadow=0,
    ZTitleOpacity=1.0,
    FacesToRender=63,
    CullBackface=0,
    CullFrontface=1,
    ShowGrid=0,
    ShowEdges=1,
    ShowTicks=1,
    LabelUniqueEdgesOnly=1,
    AxesToLabel=63,
    XLabelFontFamily='Arial',
    XLabelFontFile='',
    XLabelBold=0,
    XLabelItalic=0,
    XLabelFontSize=12,
    XLabelShadow=0,
    XLabelOpacity=1.0,
    YLabelFontFamily='Arial',
    YLabelFontFile='',
    YLabelBold=0,
    YLabelItalic=0,
    YLabelFontSize=12,
    YLabelShadow=0,
    YLabelOpacity=1.0,
    ZLabelFontFamily='Arial',
    ZLabelFontFile='',
    ZLabelBold=0,
    ZLabelItalic=0,
    ZLabelFontSize=12,
    ZLabelShadow=0,
    ZLabelOpacity=1.0,
    XAxisNotation='Mixed',
    XAxisPrecision=2,
    XAxisUseCustomLabels=0,
    XAxisLabels=[],
    YAxisNotation='Mixed',
    YAxisPrecision=2,
    YAxisUseCustomLabels=0,
    YAxisLabels=[],
    ZAxisNotation='Mixed',
    ZAxisPrecision=2,
    ZAxisUseCustomLabels=0,
    ZAxisLabels=[],
    UseCustomBounds=0,
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
)

# init the 'Polar Axes Representation' selected for 'PolarAxes'
threshold1Display.PolarAxes.Set(
    Visibility=0,
    Translation=[0.0, 0.0, 0.0],
    Scale=[1.0, 1.0, 1.0],
    Orientation=[0.0, 0.0, 0.0],
    EnableCustomBounds=[0, 0, 0],
    CustomBounds=[0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
    EnableCustomRange=0,
    CustomRange=[0.0, 1.0],
    AutoPole=1,
    PolarAxisVisibility=1,
    RadialAxesVisibility=1,
    DrawRadialGridlines=1,
    PolarArcsVisibility=1,
    DrawPolarArcsGridlines=1,
    NumberOfRadialAxes=0,
    DeltaAngleRadialAxes=45.0,
    NumberOfArcs=5,
    DeltaRangeArcs=0.0,
    CustomMinRadius=1,
    MinimumRadius=0.0,
    CustomMaxRadius=0,
    MaximumRadius=1.0,
    CustomAngles=1,
    MinimumAngle=0.0,
    MaximumAngle=90.0,
    RadialAxesOriginToPolarAxis=1,
    PolarArcResolutionPerDegree=0.2,
    Ratio=1.0,
    EnableOverallColor=1,
    OverallColor=[1.0, 1.0, 1.0],
    PolarAxisColor=[1.0, 1.0, 1.0],
    PolarArcsColor=[1.0, 1.0, 1.0],
    LastRadialAxisColor=[1.0, 1.0, 1.0],
    SecondaryPolarArcsColor=[1.0, 1.0, 1.0],
    SecondaryRadialAxesColor=[1.0, 1.0, 1.0],
    PolarAxisTitleVisibility=1,
    PolarAxisTitle='Radial Distance',
    PolarAxisTitleLocation='Bottom',
    PolarTitleOffset=[20.0, 20.0],
    PolarLabelVisibility=1,
    PolarLabelFormat='%-#6.3g',
    PolarLabelExponentLocation='Labels',
    PolarLabelOffset=10.0,
    PolarExponentOffset=5.0,
    RadialLabelVisibility=1,
    RadialLabelFormat='%-#3.1f',
    RadialLabelLocation='Bottom',
    RadialLabelOffset=[20.0, 0.0],
    RadialUnitsVisibility=1,
    ScreenSize=10.0,
    PolarAxisTitleOpacity=1.0,
    PolarAxisTitleFontFamily='Arial',
    PolarAxisTitleFontFile='',
    PolarAxisTitleBold=0,
    PolarAxisTitleItalic=0,
    PolarAxisTitleShadow=0,
    PolarAxisTitleFontSize=12,
    PolarAxisLabelOpacity=1.0,
    PolarAxisLabelFontFamily='Arial',
    PolarAxisLabelFontFile='',
    PolarAxisLabelBold=0,
    PolarAxisLabelItalic=0,
    PolarAxisLabelShadow=0,
    PolarAxisLabelFontSize=12,
    LastRadialAxisTextOpacity=1.0,
    LastRadialAxisTextFontFamily='Arial',
    LastRadialAxisTextFontFile='',
    LastRadialAxisTextBold=0,
    LastRadialAxisTextItalic=0,
    LastRadialAxisTextShadow=0,
    LastRadialAxisTextFontSize=12,
    SecondaryRadialAxesTextOpacity=1.0,
    SecondaryRadialAxesTextFontFamily='Arial',
    SecondaryRadialAxesTextFontFile='',
    SecondaryRadialAxesTextBold=0,
    SecondaryRadialAxesTextItalic=0,
    SecondaryRadialAxesTextShadow=0,
    SecondaryRadialAxesTextFontSize=12,
    EnableDistanceLOD=1,
    DistanceLODThreshold=0.7,
    EnableViewAngleLOD=1,
    ViewAngleLODThreshold=0.7,
    SmallestVisiblePolarAngle=0.5,
    AllTicksVisibility=1,
    ArcTicksOriginToPolarAxis=1,
    TickLocation='Both',
    AxisTickVisibility=1,
    AxisMinorTickVisibility=0,
    AxisTickMatchesPolarAxes=1,
    DeltaRangeMajor=1.0,
    DeltaRangeMinor=0.5,
    ArcTickVisibility=1,
    ArcMinorTickVisibility=0,
    ArcTickMatchesRadialAxes=1,
    DeltaAngleMajor=10.0,
    DeltaAngleMinor=5.0,
    TickRatioRadiusSize=0.02,
    PolarAxisMajorTickSize=0.0,
    PolarAxisTickRatioSize=0.3,
    PolarAxisMajorTickThickness=1.0,
    PolarAxisTickRatioThickness=0.5,
    LastRadialAxisMajorTickSize=0.0,
    LastRadialAxisTickRatioSize=0.3,
    LastRadialAxisMajorTickThickness=1.0,
    LastRadialAxisTickRatioThickness=0.5,
    ArcMajorTickSize=0.0,
    ArcTickRatioSize=0.3,
    ArcMajorTickThickness=1.0,
    ArcTickRatioThickness=0.5,
    Use2DMode=0,
    UseLogAxis=0,
)

# hide data in view
Hide(calculator2, renderView1)

# update the view to ensure updated data information
renderView1.Update()

renderView1.ResetActiveCameraToNegativeZ()

# reset view to fit data
renderView1.ResetCamera(False, 0.9)

#================================================================
# addendum: following script captures some of the application
# state to faithfully reproduce the visualization during playback
#================================================================

# get layout
layout1 = GetLayout()

#--------------------------------
# saving layout sizes for layouts

# layout/tab size in pixels
layout1.SetSize(3120, 1558)

#-----------------------------------
# saving camera placements for views

# current camera placement for renderView1
renderView1.Set(
    CameraPosition=[0.0, 0.0, 6.692130429902463],
    CameraFocalPoint=[0.0, 0.0, -1e-20],
    CameraParallelScale=1.7320508075688772,
)


##--------------------------------------------
## You may need to add some code at the end of this python script depending on your usage, eg:
#
## Render all views to see them appears
# RenderAllViews()
#
## Interact with the view, usefull when running from pvpython
# Interact()
#
## Save a screenshot of the active view
# SaveScreenshot("path/to/screenshot.png")
#
## Save a screenshot of a layout (multiple splitted view)
# SaveScreenshot("path/to/screenshot.png", GetLayout())
#
## Save all "Extractors" from the pipeline browser
# SaveExtracts()
#
## Save a animation of the current active view
# SaveAnimation()
#
## Please refer to the documentation of paraview.simple
## https://www.paraview.org/paraview-docs/nightly/python/
##--------------------------------------------